// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa-0KJ-0Z1S23viuA_UpWGRLEvqB2wFiM',
    appId: '1:800177989153:web:76ab0043159573a923e560',
    messagingSenderId: '800177989153',
    projectId: 'login-bcf11',
    authDomain: 'login-bcf11.firebaseapp.com',
    storageBucket: 'login-bcf11.appspot.com',
    measurementId: 'G-3E0F82RWJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0-AavYpSN_7DmNdF8PuGBdUwlKFhfDg',
    appId: '1:800177989153:android:1a44a213b3421f1e23e560',
    messagingSenderId: '800177989153',
    projectId: 'login-bcf11',
    storageBucket: 'login-bcf11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZZKQxNbrMaMcrlz4S4QMvaUgt_-DwAY',
    appId: '1:800177989153:ios:e292acadc3203d3323e560',
    messagingSenderId: '800177989153',
    projectId: 'login-bcf11',
    storageBucket: 'login-bcf11.appspot.com',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZZKQxNbrMaMcrlz4S4QMvaUgt_-DwAY',
    appId: '1:800177989153:ios:e292acadc3203d3323e560',
    messagingSenderId: '800177989153',
    projectId: 'login-bcf11',
    storageBucket: 'login-bcf11.appspot.com',
    iosBundleId: 'com.example.schedule',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa-0KJ-0Z1S23viuA_UpWGRLEvqB2wFiM',
    appId: '1:800177989153:web:3e067bbf35b254ed23e560',
    messagingSenderId: '800177989153',
    projectId: 'login-bcf11',
    authDomain: 'login-bcf11.firebaseapp.com',
    storageBucket: 'login-bcf11.appspot.com',
    measurementId: 'G-WE5ETYDMDY',
  );

}